# إعدادات الموقع الأساسية
url: "https://omrhmza.github.io"
baseurl: "" 
favicon: "/favicon.ico"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # الستايل الداكن
title: "عمر حمزة"
subtitle: "الشاعر الجديد"
locale: "ar" # تم تحديده للعربية السورية لتحسين الخطوط

# إثبات ملكية جوجل (Google Search Console)
google_site_verification: "N9JY6LXUKKkpnflfLJnIrEUa3HJ3HdJXAFAdjkLtaUc"

# إعدادات البحث
search: true
search_full_content: true

# الإضافات (Plugins)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag # إضافة أساسية لربط الميتا تاج تلقائياً

# إعدادات الترقيم (Pagination) لصفحة المقالات
paginate: 10
paginate_path: "/page:num/"

# إعدادات الكاتب
author:
  name: "عمر حمزة"
   # تأكد من وجود صورة بهذا المسار أو غيره
  bio: "أنا شاب سوري أدرس اللغة الإنكليزية... مهتم بالأدب بشكل عام... والشعر العربي العمودي بشكل خاص..."
  location: "الجمهورية العربية السورية"
  home: "/about/"
  links:
    - label: "تويتر"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/omrhmza"
    - label: "عني"
      icon: "fas fa-fw fa-user"
      url: "/about/"

# إعدادات الأرشيف التلقائي
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# تعليقات Giscus
comments:
  provider: "custom"

# إعدادات مسار التنقل (Breadcrumbs)
breadcrumbs: true

# الإعدادات الافتراضية (Defaults)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
      show_date: true
      read_time: true      
      words_per_minute: 150
      breadcrumbs: true    
      toc: true
      toc_label: "محتويات القصيدة/المقال"
      toc_icon: "align-right"
  
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# إعدادات الروابط الدائمة
permalink: /:categories/:title/
